config/routes.rb
Rails.application.routes.draw do
  resources :documents
  get 'study/index'
  post "documents/convert/:id", to: "documents#convert", as: :convert
 
  
 resources :outputs do
  resources :comments
 end
 
  resources :outputs do
  resources :fileviews
 end
 
 
  root 'study#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :output
end

app/models/document.rb
class Document < ApplicationRecord
  has_attached_file :media
  validates_attachment_content_type :media, :content_type => ['application/pdf', 'application/msword', 'application/rtf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]

  def pdf_url
    pdf_split_url = media.url.split("/")
	pdf_split_url.pop
	pdf_split_url.join("/") + "/#{base_name}.pdf"
  end

  def to_pdf
    if id && ["docx", "doc", "rtf"].include?(extension)
      ::Libreconv.convert(media.path, "#{base_path}/#{base_name}.pdf")
	end
    true
  end

  def extension
    media_file_name.split(".").second
  end

  def base_name
    media_file_name.split(".").first
  end

  def base_path
    split_path = media.path.split("/")
    split_path.pop
	split_path.join("/")
  end
end

app/models/fileview.rb
class Fileview < ApplicationRecord
  belongs_to :output
  
  
end

 

app/models/output.rb
class Output < ApplicationRecord
  has_many :comments, dependent: :destroy   
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @output = Output.find(params[:output_id])
    @comment = @output.comments.create(comment_params)
    redirect_to output_path(@output)
  end
  
    def destroy
    @output = Output.find(params[:output_id])
    @comment = @output.comments.find(params[:id])
    @comment.destroy
    redirect_to output_path(@output)
  end
  
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @document.media = file_params

    respond_to do |format|
      if @document.save && @document.to_pdf
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if (@document.media = file_params) && @document.update(document_params) && @document.to_pdf
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def convert
    @document = Document.find document_params_id
	@document.to_pdf
	render :show
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :author)
    end

    def file_params
      params.require(:document).permit(:media)[:media] 
    end

	def document_params_id
      params.permit(:id)[:id]
	end
end

app/controllers/fileviews_controller.rb
class FileviewsController < ApplicationController

 def display
    @output = Output.find(params[:id])
	 f=File.open("app/assets/tfls/safety/"+@output.output_file_name, "r")
	 f.read
	
  end
  

end

app/controllers/outputs_controller.rb
class OutputsController < ApplicationController

  

 def index
    @outputs = Output.all
  end
 def show
    @output = Output.find(params[:id])
  end
  
   def display
    @output = Output.find(params[:id])
	 f=File.open("app/assets/tfls/safety/"+@output.output_file_name, "r")
	 f.read
	
  end
  
  

  def new
   @output = Output.new
  end
  
  def edit
  @output = Output.find(params[:id])
  end

  def create
   #render plain: params[:output].inspect
    @output = Output.new(output_params)
	if @output.save
       redirect_to @output
	else
       render 'new'
    end
  end
  
  def update
  @output = Output.find(params[:id])
 
  if @output.update(output_params)
    redirect_to @output
  else
    render 'edit'
  end
end


def destroy
  @output = Output.find(params[:id])
  @output.destroy
 
  redirect_to outputs_path
end

  
  private
  def output_params
    params.require(:output).permit(:title, :number, :TFL,
                     	:footnote, :population, :domain, :status, :program_name, :output_file_name)
  end
  
  
end
 

app/controllers/study_controller.rb
class StudyController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/fileviews_helper.rb
module FileviewsHelper
end

app/helpers/outputs_helper.rb
module OutputsHelper

 def view_output(filename)
     f=File.open("app/assets/tfls/safety/"+filename, "r")
	 f.read 
  end
  

end

app/helpers/study_helper.rb
module StudyHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.output, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @output, @output.comments.build ]) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/documents/_button_convert.html.erb
<%= form_with(model: @document, local: true, url: convert_path(@document.id), method: :post) do |form| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit "convertir" %>
  </div>
<% end %>

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	  <%= form.label :title, :required => true %>
	  <%= form.text_field :title, id: :document_title, :required => true %>
  </div>

  <div class="field">
    <%= form.label :author %>
	<%= form.text_field :author, id: :document_author, :required => true %>
  </div>

  <div class="field">
    <%= form.label :media %>
	<%= form.file_field :media, id: :media, :required => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>
<iframe src="<%= @document.pdf_url %>" style="overflow:hidden;height:700px;width:100%" height="100%" width="100%"> </iframe>
<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.title %></td>
        <td><%= document.author %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @document.author %>
</p>

<p>

<iframe src="<%= @document.pdf_url %>" style="overflow:hidden;height:700px;width:100%" height="100%" width="100%"> </iframe>
</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">First  interactive clinical Report</a>
    by <a href="http://www.cine-home.fr/">Philippe Remusat</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",   study_index_path %></li>
      <li><%= link_to "Main outputs", outputs_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    study_index_path %></li>
        <li><%= link_to "Liste",   outputs_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/outputs/_form.html.erb
 
<%= form_with scope: :output, url: outputs_path, local: true do |form| %>

  <% if @output.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@output.errors.count, "error") %> prohibited
        this output from being saved:
      </h2>
      <ul>
        <% @output.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="container">
  <div class="panel-group">
  
    <div class="panel panel-info ">
       <div class="panel-heading"><%= form.label :Domain %><br></div>
       <div class="panel-body"><%= form.text_field :domain %></div>
	</div>
	
 <div class="panel panel-info ">
       <div class="panel-heading"> <%= form.label :Type %><br></div>
       <div class="panel-body"><%= form.text_field :TFL %></div>
	</div>
 <div class="panel panel-info ">
       <div class="panel-heading"> <%= form.label :Number %><br></div>
       <div class="panel-body"><%= form.text_field :number %></div>
</div>	
 <div class="panel panel-info ">
       <div class="panel-heading"> <%= form.label :Title %><br></div>
       <div class="panel-body"><%= form.text_field :title %></div>
</div>	
 <div class="panel panel-info ">
       <div class="panel-heading">  <%= form.label :Population %><br></div>
       <div class="panel-body"><%= form.text_field :population %></div>
</div>	

 <div class="panel panel-info ">
       <div class="panel-heading"> <%= form.label :Footnote %><br></div>
       <div class="panel-body"><%= form.text_field :footnote %></div>
  </div>
  
 
 <div class="panel panel-info ">
       <div class="panel-heading"> <%= form.label :Program %>
	   <button type="button" class="btn btn-success">Create</button>
       <button type="button" class="btn btn-info">Update</button>
       <button type="button" class="btn btn-warning">Excecute</button>
	   
	   <br></div>
       <div class="panel-body"><%= form.text_field :program_name %></div>
  </div>
    
  <div class="panel panel-info "> 
       <div class="panel-heading"> <%= form.label :Filename  %>
	   <button type="button" class="btn btn-success">Open</button>
	   <br></div>
       <div class="panel-body"><%= form.text_field :output_file_name %></div>
	   
  </div> 

  
 
  
 <div class="panel panel-info ">
    <%= form.label :Status %><br>
    <%= form.text_area :status %>
  </div>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/outputs/_view.html.erb
<h3> 

<%= link_to @output.output_file_name,
    File.open("app/assets/tfls/safety/"+@output.output_file_name, "r")
	%> 

 

 

app/views/outputs/edit.html.erb
<h1>Edit output</h1>
<%= render 'form' %>
<%= link_to 'Back', outputs_path %>

app/views/outputs/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
    <%= render 'layouts/header' %>
  <body>
   <div class="container">
      <%= yield %>
<h1>Listing of outputs</h1>
 
<%= link_to 'New output', new_output_path %>
<p></p>
<table class="table table-striped">
  <thead>
  <tr>
      <th>Domain</th>
      <th>Type</th>
      <th>Number</th>
      <th>Title</th>
      <th>Population</th>
      
	  <th>Status</th>
	  <th> </th>
	  <th> </th>
	  <th> </th>
  </thead>
  </tr>
 
  <% @outputs.each do |output| %>
   <tbody>
    <tr>
      <td><%= output.domain %></td>
      <td><%= output.TFL %></td>
	  <td><%= output.number %></td>
      <td><%= output.title %></td>
	  <td><%= output.population %></td>
	  	 
      <td><%= output.status %></td>
	  
      <td><%= link_to 'Show', output_path(output) %></td>
	  <td><%= link_to 'Edit', edit_output_path(output) %></td>
	 
	  <td><%= link_to 'Destroy', output_path(output),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  
 </tbody>
</table>
<p></p>
  <%= link_to 'Back', outputs_path %>
  
    <%= render 'layouts/footer' %>
    </div>

  </body>
</html>

app/views/outputs/new.html.erb
<h1>New Output</h1>
<%= render 'form' %>
<%= link_to 'Back', outputs_path %>

app/views/outputs/show.html.erb
<div class="container">
 <div class="well well-sm">

<p>
  <strong>TFL:</strong>
  <%= @output.TFL %>
</p>


<p>
  <strong>Domain:</strong>
  <%= @output.domain %>
</p>
<p>
  <strong>Number:</strong>
  <%= @output.number %>
</p>
<p>
  <strong>Title:</strong>
  <%= @output.title %>
</p>
 <p>
  <strong>Population:</strong>
  <%= @output.population %>
</p>
<p>
  <strong>Footnote:</strong>
  <%= @output.footnote %>
</p>

<p>
  <strong>Footnote:</strong>
  <%= @output.footnote %>
</p>

<p>
  <strong>Program:</strong>
  <%= @output.program_name %>
</p>

<p>
  <strong>Output file name:</strong>
 <%= @output.output_file_name %>
</p>

 
</div  >



<strong>Comments</strong>
<%= render @output.comments %>
<p>
<strong>Add a comment:</strong>
<%= render 'comments/form' %>
</p>
 
 
<%= link_to 'Edit', edit_output_path(@output) %> |
<%= link_to 'Back', outputs_path %>

 

app/views/study/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
	  
	  	<h1>Hello, Hard Workers!</h1>
	    <%= link_to 'Study ABC1234', controller: 'outputs' %>
	  
      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>